---
application_name: ton-index-go

# ADJUST. For additional args call build/ton-index-go -help
bind_addr: ":4100"
pg_dsn: postgresql://localhost:5432/mainnet
additional_args:

# deploy config
remote_hosts: 
  - ubuntu-01
  - ubuntu-02
  - ubuntu-03
service_user: root
service_group: root
go_binary: ton-index-go
go_binary_path: /usr/local/bin
systemd_service_path: /etc/systemd/system
